AllCops:
  Include:
    - 'Rakefile'
    - '*.gemspec'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'smoke/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Rails:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
